language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql

script: npm test

before_script:
  - npm i -g sequelize-cli
  - psql -c "create database haven;" -U postgres

after_success:
  - npm run coveralls
