import passwordUtil from '../utilities/passwordHasher';

const { hash } = passwordUtil;
const password = hash('password');

const users = [
  {
    firstName: 'Queen',
    lastName: 'Darling',
    username: 'queen_109',
    email: 'queen.darling@gmail.com',
    password,
    role: 'user',
    isConfirmed: 'true',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Price',
    lastName: 'Raymonds',
    username: 'rayprice',
    email: 'praymonds@gmail.com',
    password,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Kingston',
    lastName: 'Jacob',
    username: 'jacobkings@108',
    email: 'jkings@gmail.com',
    password,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Halle',
    lastName: 'Berry',
    username: 'haleberry',
    email: 'haleberry@gmail.com',
    password,
    role: 'admin',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'James',
    lastName: 'Bond',
    username: 'jbond@wars',
    email: 'james@gmail.com',
    password,
    role: 'admin',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Wilson',
    lastName: 'Fisk',
    username: 'wilson',
    email: 'Wilson.fisk@gmail.com',
    password,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Clark',
    lastName: 'Kent',
    username: 'clark',
    email: 'clark.kent@gmail.com',
    password,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Neil',
    lastName: 'Armstrong',
    username: 'armstrong',
    email: 'neil.armstrong@gmail.com',
    password,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Raymond',
    lastName: 'Tusk',
    username: 'raymond',
    email: 'raymond.tusk@gmail.com',
    password,
    role: 'admin',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    firstName: 'Louis',
    lastName: 'Lane',
    username: 'louis',
    email: 'louis.lane@gmail.com',
    password,
    role: 'user',
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

export default users;
